### ISSUE TITLE
[feat] 노약자일 경우 기능 추가

### ISSUE THREAD

**Issue by minwoo0419** [TelePigeon/TelePigeon-Server#116]
## Issue 📌
[//]: # (전체 작업에 대해 간략한 설명)

## Todo ✔️
[//]: # (해야할 일 간단한 체크리스트)
- [ ] profile에 easyMode 테이블 추가
- [ ] 추가정보 조회/수정 api에 추가
- [ ] 질문 조회 api에 추가
