### ISSUE TITLE
[feat] Room 관련 API 생성

### ISSUE THREAD

**Issue by kmjenny** [TelePigeon/TelePigeon-Server#21]
## Issue 📌
Room 관련 API 생성

## Todo ✔️
- [x] Room 목록 API
- [x] Room 삭제 API
- [x] Room 입장 API
- [x] Room 정보 가져오기 API
