### ISSUE TITLE
[feat] Domain 생성

### ISSUE THREAD

**Issue by minwoo0419** [TelePigeon/TelePigeon-Server#3]
## Issue 📌
ER Table을 바탕으로 Domain을 만듭니다.

## Todo ✔️
[//]: # (해야할 일 간단한 체크리스트)
- [ ] Users Domain 구현
- [ ] Profile Domain 구현
- [ ] Room Domain 구현
- [ ] Worry Domain 구현
- [ ] WorryTime Domain 구현
- [ ] Answer Domain 구현
- [ ] Question Domain 구현

**Comment by jihyunniiii** [comment]
도용 금지세요 ;;
