### ISSUE TITLE
[refac] 개선사항 적용

### ISSUE THREAD

**Issue by tkdwns414** [TelePigeon/TelePigeon-Server#9]
## Issue 📌
[//]: # (전체 작업에 대해 간략한 설명)
전체적인 개선 사항에 대한 적용을 위한 PR입니다.
- 봉투 패턴 적용 방법 변경 및 봉투 변경
- CustomException 세분화

## Todo ✔️
[//]: # (해야할 일 간단한 체크리스트)
- [x] ResponseBodyAdvice의 역할을 'HttpStatus 변경'에서 '봉투 적용'으로 변경
- [x] HttpStatus는 ResponseStatus를 사용하도록 변경
- [x] CustomException 세분화
- [x] 일부 패키지 이동
